### ISSUE TITLE
connection bleak timeout error from central device

### ISSUE THREAD

**Issue by ethanHuntoo7** [adafruit/Adafruit_Blinka_bleio#28]
Python version: 3.7
Operating System: raspbian buster-lite
BlueZ version (bluetoothctl -v) in case of Linux: 5.50
Description
I was simply trying to connect a peripheral device with a central device using bleak nordic service

What I Did
first I ran a peripheral device with an advertisement that can be seen in my android scanning ble app

then in central deivce I just ran client code in the below link https://github.com/adafruit/Adafruit_CircuitPython_BLE/blob/master/examples/ble_uart_echo_client.py

it start scanning and then scanning stop after trying to make a connection with the bellow error

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/bleak/backends/bluezdbus/client.py", line 135, in connect
    ).asFuture(loop)
txdbus.error.RemoteError: org.freedesktop.DBus.Error.UnknownObject: Method "Connect" with signature "" on interface "org.bluez.Device1" doesn't exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testClient.py", line 33, in <module>
    ble.connect(advertisement)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_ble/__init__.py", line 305, in connect
    connection = self._adapter.connect(advertisement.address, timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/_bleio/adapter_.py", line 373, in connect
    return self.await_bleak(self._connect_async(address, timeout=timeout))
  File "/usr/local/lib/python3.7/dist-packages/_bleio/adapter_.py", line 134, in await_bleak
    return future.result(timeout)
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/dist-packages/_bleio/adapter_.py", line 384, in _connect_async
    await client.connect(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/bleak/backends/bluezdbus/client.py", line 142, in connect
    self.address
bleak.exc.BleakError: Device with address b8:27:eb:96:30:96 could not be found. Try increasing `timeout` value or moving the device closer.

**Comment by dhalbert** [comment]
Which RPI board are you using? There's a bug in the Bluetooth firmware that affects 3B+ and 4B. See https://learn.adafruit.com/circuitpython-ble-libraries-on-any-computer/install-ble-libraries#raspberry-pi-3b-plus-and-4b-firmware-fix-3074928-6.

Also, which version of bleak and the other BLE libraries do you have installed? Do `pip3 list | grep ble` and paste the output here. Bleak has had new releases recently and I need to re-test.

**Comment by ethanHuntoo7** [comment]
> Which RPI board are you using? There's a bug in the Bluetooth firmware that affects 3B+ and 4B. See https://learn.adafruit.com/circuitpython-ble-libraries-on-any-computer/install-ble-libraries#raspberry-pi-3b-plus-and-4b-firmware-fix-3074928-6.
> 
> Also, which version of bleak and the other BLE libraries do you have installed? Do `pip3 list | grep ble` and paste the output here. Bleak has had new releases recently and I need to re-test.

adafruit-blinka-bleio         2.0.4
adafruit-circuitpython-ble    7.3.1
bleak                         0.9.1

**Comment by ethanHuntoo7** [comment]
Can you give me any clue about this.

I'm using your this Client code

https://github.com/adafruit/Adafruit_CircuitPython_BLE/blob/master/examples/ble_uart_echo_client.py

And for peripheral I'm using

https://scribles.net/creating-ble-gatt-server-uart-service-on-raspberry-pi/

**Comment by dhalbert** [comment]
Did you try the 'rpt2' version of the firmware on the RPi 3B+ as mentioned in https://learn.adafruit.com/circuitpython-ble-libraries-on-any-computer/install-ble-libraries#raspberry-pi-3b-plus-and-4b-firmware-fix-3074928-6 ? The scribles.net peripheral code might not work properly on the 3B+ with the bad firmware.

**Comment by ethanHuntoo7** [comment]
Okay I will try the rpt2 version but this
https://scribles.net/creating-ble-gatt-server-uart-service-on-raspberry-pi/
code is working fine in my all 8-10 raspberry Pi Zero W and even in my
Raspberry 3b+ it's working great with both Android and iOS client scanner
app. So I think it should work with your
https://github.com/adafruit/Adafruit_CircuitPython_BLE/blob/master/examples/ble_uart_echo_client.py
too

**Comment by dhalbert** [comment]
The `rpt8` version of the firmware has the bug I mentioned fixed.

Are you still having other troubles?

**Comment by NR5P** [comment]
```
bleak.exc.BleakError: Device with address f4:cf:a2:8d:30:fa could not be found. Try increasing `timeout` value or moving the device closer.
```
I'm having same issue. I've confirmed I'm at rpt8 version of firmware and library versions are 
```
adafruit-blinka-bleio         2.2.0      
adafruit-circuitpython-ble    8.0.0      
bleak                         0.11.0     
```

I can see the device in scan but when connecting I'm getting the error. My last hurtle of the project I'm working on and this has been driving me nuts :D. 

code
```
from adafruit_ble import BLERadio
from adafruit_ble.advertising.standard import ProvideServicesAdvertisement
from adafruit_ble.services.nordic import UARTService

ble = BLERadio()
device_addr = "f4:cf:a2:8d:30:fa"
print("scanning")
found = set()
scan_responses = set()
uart_connection = None
for advertisement in ble.start_scan():
    if device_addr.lower() in str(advertisement.address):
        addr = advertisement.address
        print(addr)
        #print(advertisement.services) 
        uart_connection = ble.connect(advertisement) 
        if advertisement.scan_response and addr not in scan_responses:
            scan_responses.add(addr)
        elif not advertisement.scan_response and addr not in found:
            found.add(addr)
        else:
            continue
        print(addr, advertisement)
        print("\t" + repr(advertisement))
        print()

print("scan done")

print(ble.connected)
while ble.connected:
    one_byte = ble.read(1)
    print(one_byte)

```

**Comment by dhalbert** [comment]
@NR5P Several things changed in the `bleak` bump to 0.11.0, so it's possible we're . You could try 0.10.0 and see if it works. You may need to downgrade adafruit-blinka-bleio to the previous version too - I am not sure.

Are you also trying on RPi (which board?), and `bluez-firmware` at `rpt8`?
